### ISSUE TITLE
Use am/pm in time picker? (or allow user to type in date/time?)

### ISSUE THREAD

**Issue by patudom** [cosmicds/blaze-star-nova#13]
In #10, I wasn't able to type numbers into the time dial, so if you want to change from 6am to 6pm, it's a lot of clicks. I'm wondering if it might be worth sticking with a 12 hr clock (instead of 24) and adding an am/pm dial; or making it so that you can type in the desired time. I'm thinking the former would still be more intuitive. I'm not sure everyone would figure out that you could type into the boxes if we made that possible, but I'm happy to go with what you guys think.

**Comment by johnarban** [comment]
I had originally tried with input boxes the user could enter  numbers in, but ran into issues (like you can't zero-pad the values). I can also try to make it something where it is a select box and by clicking on it opens a list of options. 

For now I will do that AM/PM thing. I think most people will hit that and go +- a couple hours.  

And then play around with other options later. 

the old VueDatePicker, that automatically allows users to type dates (and will figure out the format for you), and maybe I can do something with that, but I think that would be much lower priority

**Comment by johnarban** [comment]
In #16 I have made it an am/pm time picker (configurable with a prop)
