### ISSUE TITLE
horizon/sky still jitters

### ISSUE THREAD

**Issue by patudom** [cosmicds/blaze-star-nova#14]
I think it was my todo item to experiment with time values to minimize the horizon/sky jitter while advancing time. Can I pass this back to @johnarban or @Carifio24? In #10, the jitter is very obvious when it's daytime and there is more contrast between the blue sky & the dark horizon. It's still there (but less noticeable) when it's nighttime.

**Comment by johnarban** [comment]
I have addressed this in #16 by reducing the interval to 10ms.

**Comment by johnarban** [comment]
This I believe has been solved. Perhaps there is something that can be done so that it doesn't happen for any update speed (@Carifio24 ), but this is good for now.
