### ISSUE TITLE
General Setup

### ISSUE THREAD

**Issue by patudom** [cosmicds/blaze-star-nova#2]
WWT stuff (Jon, except for tour)
- [x] Start at location just btw CrB & Bootes
- [x] Overlay showing location of T CrB - "Blaze Star"
- [x] Separate overlay for alpha CrB - "Nova will be roughly this bright"
- [x] Show constellation names & outlines (make these on/off toggles in control menu)
- [x] NESW labels on horizon (in Eclipse)
- [x] Make sure horizon updates with time (in Eclipse)
- [x] When CrB is below the horizon, put a note on screen that says "Corona Borealis is set"
- [x] When sun is above the horizon, make sky blue  (in Eclipse)
- [x] 2-3 slide tour showing how to find Corona Borealis (Pat)
- [x] Change default background to Tycho synthetic stars.
- [x] Add button that changes to USNOB to show how nova will appear after it blows.

Other stuff (John)
- [x] Start at "today" at 9pm by default
- [x] Add a date picker
- [x] Add a time picker
- [x] Play/pause button at 1000x speed
- [x] Add location picker (in Eclipse)
- [x] Date & Time display (in Eclipse - but we might style this one differently)

Informational content
- [x] Draft info text (Pat)

**Comment by Carifio24** [comment]
The starting location, NSEW labels, and constellation figures are handled in #3. The horizon and sky updating with time, along with the "Corona Borealis is set" note are in #4.

I've made some good progress on the text annotations, but they aren't quite done yet.
