### ISSUE TITLE
Handle user time zones

### ISSUE THREAD

**Issue by johnarban** [cosmicds/blaze-star-nova#21]
When the use selects a location, we need to get the location and timezone offset. There are a couple options. we can have 

- The "local time" stay the same, so if I am 9pm in boston, then if I select Seattle, it will be 9pm in seattle
- The "local time" stay constant, so if I am 9pm in boston, then if I select Seattle, it will be 6pm in seattle

We will want a writable computed `localSelectedTime`, since the DateTimePicker is not timezone aware.

**Comment by Carifio24** [comment]
I guess I would suspect people would want the first option - that they're changing the time zone because they realized the time that they put in isn't actually that time for them. But I'm fine with either way.
