### ISSUE TITLE
Go to T CrB button should use the displayed time

### ISSUE THREAD

**Issue by patudom** [cosmicds/blaze-star-nova#30]
The time controls say it is 9pm, but the "go to T CrB" button takes me to a daytime version of T CrB, so I think it is using "now" instead of the time in the time controls. It should go to T CrB at whatever time is being displayed.

<img width="1283" alt="Screenshot 2024-08-20 at 3 56 20 PM" src="https://github.com/user-attachments/assets/b8b01f2f-b8d9-4391-b6da-ac549136110c">

**Comment by Carifio24** [comment]
I'm not able to reproduce this - the condition of the sky doesn't change for me when I use the "Go to T CrB"button.

**Comment by patudom** [comment]
I can no longer reproduce this either. Hopefully my computer was just in a weird state that won't happen to everyone else. I will close this for now and we can reopen if we see this again.

**Comment by patudom** [comment]
Just got it to happen again, on #35, where I would expect this not to happen. As I noted to @Carifio24 on Slack, the time seems to get really confused if you start running the tour while time is already playing forward, so we should always pause time before we start running the tour.
<img width="1312" alt="Screenshot 2024-08-21 at 2 42 57 PM" src="https://github.com/user-attachments/assets/9f0f637f-e2e5-4064-99f8-05d180418496">


https://github.com/user-attachments/assets/40948f01-9e95-4e6a-85b0-06d63efb27c4

**Comment by patudom** [comment]
#35 pauses time before the tour runs, so this should no longer be an issue.
